on: push
name: CI
jobs:
  test:
    name: Test Suite
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.1,name=iPhone 12 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          set -o pipefail && xcodebuild -scheme ForemWebView -sdk iphonesimulator -destination "${destination}" test | xcpretty
        env:
         DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
         destination: ${{ matrix.destination }}
